import React from 'react';
import { createRoot } from 'react-dom/client';
import { palettes,fonts,roles,pairings,semanticTokens,contrast } from './theme-data.mjs';

const api=window.HoeaAppearance;
const host=document.createElement('dialog');host.className='ap-dialog';host.setAttribute('aria-label','Site-wide colours and typography');document.body.append(host);
let trigger=null;
function open(event){trigger=event?.currentTarget||document.activeElement;host.showModal();}
window.addEventListener('hoea:open-appearance',()=>open({currentTarget:launcher}));
host.addEventListener('click',event=>{if(event.target===host){const r=host.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)host.close();}});
host.addEventListener('close',()=>trigger?.focus({preventScroll:true}));
// Separate entry point is available on every route, including the brand reference.
const launcher=document.createElement('button');launcher.className='ap-launcher';launcher.type='button';launcher.setAttribute('aria-label','Open colours and typography');launcher.setAttribute('aria-haspopup','dialog');launcher.innerHTML='<span aria-hidden="true">◐</span> Colours & type';launcher.addEventListener('click',open);document.body.append(launcher);
function App(){
  const [state,setState]=React.useState(api.getState),[tab,setTab]=React.useState('colour'),[mode,setMode]=React.useState(document.documentElement.dataset.theme||'light'),[notice,setNotice]=React.useState('');
  React.useEffect(()=>{const update=()=>setState(api.getState()),updateMode=()=>setMode(document.documentElement.dataset.theme||'light');window.addEventListener('hoea:appearance',update);window.addEventListener('hoea:mode',updateMode);return()=>{window.removeEventListener('hoea:appearance',update);window.removeEventListener('hoea:mode',updateMode);};},[]);
  const palette=palettes.find(p=>p.id===state.palette),tokens=semanticTokens(palette,mode==='dark');
  const selected=pairings.find(p=>p.id===state.pairing);
  function choosePalette(id){api.setPalette(id);setNotice(`${palettes.find(p=>p.id===id).name} applied across the site.`);}
  const sampleStyle={'--sample-display':fonts.find(f=>f.id===state.roles.display).stack,'--sample-body':fonts.find(f=>f.id===state.roles.body).stack};
  const exportChoices=()=>{if(window.HoeaDesignStudio?.export){window.HoeaDesignStudio.export();return;}let layouts={};try{layouts=JSON.parse(localStorage.getItem('hoea-design-studio-v1')||'{}');}catch{}const blob=new Blob([JSON.stringify({appearance:state,mode,layouts},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='hoea-site-design.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Colour, typography and layout choices exported.');};
  return <>
    <header className="ap-header"><div><span className="ap-overline">SITE-WIDE FOUNDATIONS</span><h2>Make it feel like you.</h2><p>One palette. One type system. Every component.</p></div><button className="ap-close" aria-label="Close colours and typography" onClick={()=>host.close()}>×</button></header>
    <div className="ap-toolbar"><div className="ap-tabs" role="tablist" aria-label="Appearance settings">{[['colour','Colour themes'],['type','Typography']].map(([id,label],index)=><button id={`ap-tab-${id}`} key={id} role="tab" aria-selected={tab===id} aria-controls={`ap-panel-${id}`} tabIndex={tab===id?0:-1} onClick={()=>setTab(id)} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?'colour':e.key==='End'?'type':index===0?'type':'colour';setTab(next);document.getElementById(`ap-tab-${next}`).focus();}}}>{label}</button>)}</div><div className="ap-mode" role="group" aria-label="Colour mode">{['light','dark'].map(value=><button key={value} aria-pressed={mode===value} onClick={()=>api.setMode(value)}>{value==='light'?'☀ Light':'☾ Dark'}</button>)}</div></div>
    <div className="ap-content">
      <section id="ap-panel-colour" role="tabpanel" aria-labelledby="ap-tab-colour" hidden={tab!=='colour'}>
        <div className="ap-section-title"><h3>10 palettes, with a point of view.</h3><span>01 / COLOUR</span></div><p className="ap-explainer">Mixed hues, considered neutrals and a full range of shades. Choose a palette to recolour all 51 layout options, including cards, buttons and forms.</p>
        <div className="ap-palette-grid">{palettes.map((p,index)=><button className="ap-palette" key={p.id} aria-pressed={state.palette===p.id} onClick={()=>choosePalette(p.id)}><span className="ap-swatches" aria-hidden="true">{p.colours.map(c=><i key={c} style={{background:c}}/>)}</span><span className="ap-palette-title"><strong>{p.name}</strong><span>{state.palette===p.id?'✓':String(index+1).padStart(2,'0')}</span></span><small>{p.note}</small></button>)}</div>
        <div className="ap-palette-detail"><span className="ap-overline">IN THE MIX · {palette.name}</span><p>{palette.story}</p><div className="ap-token-samples">{[['Canvas','bg'],['Surface','surface'],['Action','action'],['Accent','accent'],['Highlight','highlight'],['Atmosphere','soft']].map(([label,id])=><div key={id}><i style={{background:tokens[id],color:id==='action'?tokens['on-action']:id==='accent'?tokens['on-accent']:id==='highlight'?tokens['on-highlight']:tokens.ink}}>Aa</i><span>{label}</span><code>{tokens[id]}</code></div>)}</div><details className="ap-shades"><summary>Explore all 60 shades</summary>{palette.colours.map((colour,index)=><div key={colour}><span>{['Anchor','Counterpoint','Highlight','Atmosphere','Neutral'][index]}</span><div>{Array.from({length:12},(_,i)=><i key={i} title={`${['Anchor','Counterpoint','Highlight','Atmosphere','Neutral'][index]} ${i+1}`} style={{background:`var(--ramp-${index}-${i+1})`}}/>)}</div></div>)}</details><p className="ap-contrast">Text / canvas {contrast(tokens.ink,tokens.bg).toFixed(1)}:1 · Button label {contrast(tokens['on-action'],tokens.action).toFixed(1)}:1</p></div>
      </section>
      <section id="ap-panel-type" role="tabpanel" aria-labelledby="ap-tab-type" hidden={tab!=='type'}>
        <div className="ap-section-title"><h3>A voice for every layer.</h3><span>02 / TYPOGRAPHY</span></div><p className="ap-explainer">Start with one of 10 considered pairings, then choose any of the 10 font families for each text role.</p>
        <label className="ap-pairing-label" htmlFor="ap-pairing">Suggested pairing</label><select id="ap-pairing" value={state.pairing} onChange={e=>{api.setPairing(e.target.value);setNotice('Typography pairing applied across the site.');}}><option value="custom" disabled>Custom role choices</option>{pairings.map(p=><option key={p.id} value={p.id}>{p.name} — {fonts.find(f=>f.id===p.roles.display).name} / {fonts.find(f=>f.id===p.roles.body).name}</option>)}</select><p className="ap-pairing-note">{selected?.note||'Your own combination. Every role stays synchronised across components.'}</p>
        <div className="ap-type-specimen" style={sampleStyle}><span className="ap-sample-eyebrow">A LITTLE COURAGE, EVERY DAY</span><h3>Find your own<br/><em>way forward.</em></h3><p>Resilience is something we practise. Notice the current, connect with what matters, and choose your next step.</p><span className="ap-sample-caption">Hoea tō Waka · Ōtautahi, Aotearoa<br/>Ā Ē Ī Ō Ū · ā ē ī ō ū</span><span className="ap-sample-button">Explore the possibilities ↗</span></div>
        <div className="ap-role-list">{roles.map(role=><div className="ap-role" key={role.id}><label htmlFor={`ap-font-${role.id}`}><strong>{role.name}</strong><small>{role.note}</small></label><select id={`ap-font-${role.id}`} value={state.roles[role.id]} onChange={e=>{api.setRole(role.id,e.target.value);setNotice(`${role.name} updated across the site.`);}}>{fonts.map(font=><option key={font.id} value={font.id}>{font.name}</option>)}</select><span className="ap-role-preview" style={{fontFamily:fonts.find(f=>f.id===state.roles[role.id]).stack}}>Hoea tō Waka — a new perspective.</span></div>)}</div>
        <p className="ap-explainer">All 10 families are free, locally hosted and include Māori macrons.</p>
      </section>
    </div>
    <footer className="ap-footer"><div><strong>{palette.name}</strong><span>{selected?.name||'Custom typography'} · Saved in this browser</span></div><div className="ap-footer-actions"><button onClick={exportChoices}>Export</button><button onClick={()=>{api.reset();setNotice('Default palette and typography restored.');}}>Reset colours & type</button><button className="ap-done" onClick={()=>host.close()}>Done ↗</button></div></footer><p className="ap-status" role="status">{notice}</p>
  </>;
}
createRoot(host).render(<App/>);
